-- Add visibility toggle columns to site_settings table
ALTER TABLE public.site_settings
ADD COLUMN IF NOT EXISTS hero_visible BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS features_visible BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS products_visible BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS stores_visible BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS categories_visible BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS flash_sale_visible BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS trending_visible BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS newsletter_visible BOOLEAN DEFAULT TRUE;
