// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvanbogaajleetekxolu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2YW5ib2dhYWpsZWV0ZWt4b2x1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4MDE2NTksImV4cCI6MjA3ODM3NzY1OX0.4NiUSKeZg9xz9R7239t69SF-mMCR6T9EmXAexxC1SVA"

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});